// Sentient's documented seven functional zones, adapted into fictional station rooms.
// Provenance and adaptation boundaries: docs/SENTIENT-RESEARCH.md.
export const rooms = [
  {
    id: 'front-door',
    number: '01',
    name: 'The Front Door',
    shortName: 'Front Door',
    designation: 'Arrival & network',
    function: 'Accounts & Network View',
    description: "The entry point to Sentient's managed-account network, connecting portfolio signals, account profiles and the people behind each property.",
    tools: [
      { name: 'Sentient Accounts', description: 'A visual account network with portfolio metrics, profile detail and performance context.' },
      { name: 'Flagship Accounts', description: 'The public Sentient story introduces its media properties and client network here.' },
    ],
    x: 0,
    z: -52,
    w: 24,
    d: 18,
    mission: 'Scan the arrival terminal to establish the station network link.',
    signal: 'Network',
  },
  {
    id: 'floor',
    number: '02',
    name: 'The Floor',
    shortName: 'Floor',
    designation: 'Production deck',
    function: 'Production Tools & Utilities',
    description: 'The working production floor: reusable systems for sourcing, designing, formatting and exporting creative assets, supporting campaigns and brand growth.',
    tools: [
      { name: 'Maxx Tools', description: 'A hub for internal production and research utilities.' },
      { name: 'Reddit Visualizer', description: 'Transforms Reddit content into visual assets.' },
      { name: 'X / Tweet Visualizer', description: 'Creates customizable X post mockups and PNG exports.' },
      { name: 'Chart Animator', description: 'Builds still and animated charts for social publishing.' },
      { name: 'Schedulr', description: 'Connects planning, sourced feeds, account boards and production intake.' },
      { name: 'Social Brain', description: 'Turns article URLs into social copy and editable carousel creatives.' },
      { name: 'Posts Production Library', description: 'Reusable editorial overlays, campaign carousels and prompt-card systems.' },
      { name: 'Battle Giveaway', description: 'An Instagram utility included in the original Hub inventory.' },
      { name: 'QR Code Generator', description: 'A recovery slot in the original Hub inventory for a requested utility.' },
    ],
    x: -23,
    z: 15,
    w: 24,
    d: 20,
    mission: 'Scan the production terminal to synchronize the creative signal.',
    signal: 'Creation',
  },
  {
    id: 'archive',
    number: '03',
    name: 'The Archive',
    shortName: 'Archive',
    designation: 'Intelligence vault',
    function: 'Intelligence & Evidence',
    description: "Sentient's working memory brings together historical content, performance intelligence, research signals, campaign evidence and captured knowledge.",
    tools: [
      { name: 'Cortex by Sentient', description: 'Cover analysis, post intelligence, pattern exploration and A/B testing.' },
      { name: 'Tricks Dash', description: 'A searchable post archive with content and engagement filters.' },
      { name: 'Sentient Case Studies', description: 'Campaign outcomes and client case studies grounded in post data.' },
      { name: 'AI Safety Desk', description: 'A focused research view for AI safety, governance and risk signals.' },
      { name: 'BCCR FX Intelligence', description: 'Reference-rate tracking and economic trend context.' },
      { name: 'Slack Link Catcher', description: 'Knowledge intake with captured links, notes, categories and reminders.' },
    ],
    x: -22,
    z: -12,
    w: 22,
    d: 18,
    mission: 'Scan the archive terminal to recover the station intelligence signal.',
    signal: 'Insight',
  },
  {
    id: 'commons',
    number: '04',
    name: 'The Commons',
    shortName: 'Commons',
    designation: 'Network commons',
    function: 'Account Decks & Shared Rooms',
    description: 'A shared home for account context and collaboration. The internal Hub reserves this zone for account decks; the public website uses it to explore the creator network across social platforms.',
    tools: [
      { name: 'Account Deck Directory', description: 'The documented space reserved for account-by-account Canva decks.' },
      { name: 'Creator Network', description: 'The public company story groups creator relationships and distribution examples here.' },
      { name: 'Platform Constellation', description: 'Instagram, X, LinkedIn, TikTok and YouTube are represented in the public network story.' },
    ],
    x: 23,
    z: 23,
    w: 24,
    d: 16,
    mission: 'Scan the commons terminal to connect the collaboration signal.',
    signal: 'Connection',
  },
  {
    id: 'forum',
    number: '05',
    name: 'The Forum',
    shortName: 'Forum',
    designation: 'Strategy forum',
    function: 'Use Cases & Playbooks',
    description: 'A practical learning and strategy space for prompt systems, business use cases and content formats, complemented by the public story of Sentient’s people and mission.',
    tools: [
      { name: 'ChatGPT at Work', description: 'Practical business applications, capabilities and workflows.' },
      { name: 'ChatGPTricks Prompt Hub', description: 'Searchable prompt collections and tools for composing and saving prompts.' },
      { name: 'Content Formats', description: 'The format system spanning carousels, talking-head videos, Faceless 2.0 and reels.' },
      { name: 'People & Presence', description: 'The public website introduces the founders, team and agency mission in this room.' },
    ],
    x: 22,
    z: -3,
    w: 20,
    d: 16,
    mission: 'Scan the forum terminal to align the station strategy signal.',
    signal: 'Strategy',
  },
  {
    id: 'lab',
    number: '06',
    name: 'The Lab',
    shortName: 'Lab',
    designation: 'Experimental systems',
    function: 'Client Builds & Experiments',
    description: 'A home for client builds and experiments that have moved beyond an idea. The public website adds the campaign process: strategic setup, creative production, distribution, then tracking and scaling.',
    tools: [
      { name: 'NEO Solutions', description: 'A bilingual AI-agent website for responding to, qualifying and booking business leads.' },
      { name: 'Strategic Setup', description: 'The campaign process begins with audience fit, funnel planning and direction.' },
      { name: 'Content That Converts', description: 'Creative development connects the campaign story to its intended outcome.' },
      { name: 'Distribution', description: 'The public campaign process includes planned audience distribution.' },
      { name: 'Track & Scale', description: 'Performance data informs the next campaign decisions.' },
    ],
    x: -21,
    z: -36,
    w: 20,
    d: 16,
    mission: 'Scan the lab terminal to stabilize the experimental signal.',
    signal: 'Innovation',
  },
  {
    id: 'bridge',
    number: '07',
    name: 'The Bridge',
    shortName: 'Bridge',
    designation: 'Command & portfolio',
    function: 'Leadership & Portfolio',
    description: 'The agency control room for campaign operations, portfolio visibility and leadership. Its systems connect clients and campaigns with financial operations, onboarding and reporting.',
    tools: [
      { name: 'Sentient Promos CRM', description: 'Clients, campaigns, media outlets, margins, payments, invoices, onboarding and Instagram reporting.' },
      { name: 'Strategy Intake', description: 'The public website routes project goals into campaigns, growth systems, community or consulting.' },
      { name: 'Leadership & Portfolio', description: 'The documented Hub function brings operational visibility to the people steering the work.' },
    ],
    x: 24,
    z: -29,
    w: 26,
    d: 20,
    mission: 'Scan the command terminal to complete the leadership signal.',
    signal: 'Direction',
  },
];
